library(ggplot2)
library(cowplot)
library(gridExtra)
rm(list = ls())

VertCount <- c(133853, 53173)
VertMain <- c("Supermatrix", "Coalescent")
VertMyData <- data.frame(VertMain,VertCount)
VertMyData$VertMain <- factor(VertMyData$VertMain, levels = c("Supermatrix", "Coalescent"))
pVertMain <- ggplot(VertMyData, aes(VertMyData$VertMain,VertMyData$VertCount))
pVertMain = pVertMain + geom_bar(stat = "identity") + xlab("Topology") + ylab("Gene Count") + ggtitle("Vertebrate Two Topology Test")

VertCount2 <- c(66315, 110727, 9984)
VertMain2 <- c("Supermatrix", "Coalescent", "Alternatives")
VertMyData2 <- data.frame(VertMain2,VertCount2)
VertMyData2$VertMain2 <- factor(VertMyData2$VertMain2, levels = c("Supermatrix", "Coalescent", "Alternatives"))
pVertMain2 <- ggplot(VertMyData2, aes(VertMyData2$VertMain2,VertMyData2$VertCount2))
pVertMain2 = pVertMain2 + geom_bar(stat = "identity") + xlab("Edge") + ylab("Gene Count") + ggtitle("Vertebrate MGWE")


VertCount3 <- c(87210, 78660, 21132)
VertMain3 <- c("Supermatrix", "Coalescent", "Alternatives")
VertMyData3 <- data.frame(VertMain3,VertCount3)
VertMyData3$VertMain3 <- factor(VertMyData3$VertMain3, levels = c("Supermatrix", "Coalescent", "Alternatives"))
pVertMain3 <- ggplot(VertMyData3, aes(VertMyData3$VertMain3,VertMyData3$VertCount3))
pVertMain3 = pVertMain3 + geom_bar(stat = "identity") + xlab("Edge") + ylab("Gene Count") + ggtitle("Vertebrate MSWE")

CarCount <- c(807477, 1310106)
CarMain <- c("Supermatrix", "Coalescent")
CarMyData <- data.frame(CarMain,CarCount)
CarMyData$CarMain <- factor(CarMyData$CarMain, levels = c("Supermatrix", "Coalescent"))
pCarMain <- ggplot(CarMyData, aes(CarMyData$CarMain,CarMyData$CarCount)) 
pCarMain = pCarMain + geom_bar(stat = "identity") + xlab("Topology") + ylab("Gene Count") + ggtitle("Carnivory Two Topology Test")

CarCount2 <- c(895722, 814779, 407109)
CarMain2 <- c("Supermatrix", "Coalescent", "Alternatives")
CarMyData2 <- data.frame(CarMain2,CarCount2)
CarMyData2$CarMain2 <- factor(CarMyData2$CarMain2, levels = c("Supermatrix", "Coalescent", "Alternatives"))
pCarMain2 <- ggplot(CarMyData2, aes(CarMyData2$CarMain2,CarMyData2$CarCount2))
pCarMain2 = pCarMain2 + geom_bar(stat = "identity") + xlab("Edge") + ylab("Gene Count") + ggtitle("Carnivory MGWE")

CarCount3 <- c(537772, 740761, 837664)
CarMain3 <- c("Supermatrix", "Coalescent", "Alternatives")
CarMyData3 <- data.frame(CarMain3,CarCount3)
CarMyData3$CarMain3 <- factor(CarMyData3$CarMain3, levels = c("Supermatrix", "Coalescent", "Alternatives"))
pCarMain3 <- ggplot(CarMyData3, aes(CarMyData3$CarMain3,CarMyData3$CarCount3))
pCarMain3 = pCarMain3 + geom_bar(stat = "identity") + xlab("Edge") + ylab("Gene Count") + ggtitle("Carnivory MGWE")


plot_grid(pVertMain,pVertMain2,pVertMain3,pCarMain,pCarMain2,pCarMain3,labels=c("A","B","C","D","E","F"),ncol=3,nrow=2)
